unclassified:
  globalLibraries:
    libraries:
    - defaultVersion: "master"
      name: "gitlab-global-pipeline-library"
      retriever:
        legacySCM:
          scm:
            scmGit:
              branches:
              - name: "master"
              browser:
                gitLab:
                  repoUrl: "https://gitlab.com/MarkEWaite/pipeline-library"
                  version: "16.0"
              userRemoteConfigs:
              - url: "https://gitlab.com/MarkEWaite/pipeline-library.git"
