bundle:
  groupId: "a.b.c"
  artifactId: "jenkins"
  title: "Jenkins Custom WAR"
  description: "Custom Jenkins WAR package"
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: 2.176.2
plugins:
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ant"
    source:
      version: 1.10
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "apache-httpcomponents-client-4-api"
    source:
      version: 4.5.10-1.0
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "stashNotifier"
    source:
      version: 1.20
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "authentication-tokens"
    source:
      version: 1.3
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "bouncycastle-api"
    source:
      version: 2.17
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "branch-api"
    source:
      version: 2.5.4
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "build-name-setter"
    source:
      version: 2.0.3
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "command-launcher"
    source:
      version: 1.3
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "conditional-buildstep"
    source:
      version: 1.3.6
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "config-file-provider"
    source:
      version: 3.6.2
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "copyartifact"
    source:
      version: 1.43
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "createjobadvanced"
    source:
      version: 1.8
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: 1.20
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: 2.3.0
  - groupId: "com.cloudbees.jenkins.plugins"
    artifactId: "custom-tools-plugin"
    source:
      version: 0.7
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "display-url-api"
    source:
      version: 2.3.2
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "docker-commons"
    source:
      version: 1.15
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "docker-workflow"
    source:
      version: 1.20
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      version: 1.30
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "embeddable-build-status"
    source:
      version: 2.0.2
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "envinject-api"
    source:
      version: 1.6
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "envinject"
    source:
      version: 2.2.1
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "extended-choice-parameter"
    source:
      version: 0.78
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: 6.9
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-client"
    source:
      version: 2.8.6
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git"
    source:
      version: 3.12.1
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-server"
    source:
      version: 1.8
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jackson2-api"
    source:
      version: 2.10.0
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "javadoc"
    source:
      version: 1.5
  - groupId: "org.jenkins-ci.ui"
    artifactId: "ace-editor"
    source:
      version: 1.1
  - groupId: "org.jenkins-ci.ui"
    artifactId: "handlebars"
    source:
      version: 1.1.1
  - groupId: "org.jenkins-ci.ui"
    artifactId: "jquery-detached"
    source:
      version: 1.2.1
  - groupId: "org.jenkins-ci.ui"
    artifactId: "momentjs"
    source:
      version: 1.1.1
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jquery"
    source:
      version: 1.12.4-1
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jsch"
    source:
      version: 0.1.55.1
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "junit"
    source:
      version: 1.28
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ldap"
    source:
      version: 1.20
  - groupId: "org.6wind.jenkins"
    artifactId: "lockable-resources"
    source:
      version: 2.5
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: 1.29
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-auth"
    source:
      version: 2.4.2
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-project"
    source:
      version: 1.14
  - groupId: "org.jenkins-ci.main"
    artifactId: "maven-plugin"
    source:
      version: 3.4
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "metrics"
    source:
      version: 4.0.2.6
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jdk-tool"
    source:
      version: 1.3
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "antisamy-markup-formatter"
    source:
      version: 1.6
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "parameterized-trigger"
    source:
      version: 2.35.2
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: 2.6
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-graph-analysis"
    source:
      version: 1.10
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: 2.37
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-basic-steps"
    source:
      version: 2.18
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-build-step"
    source:
      version: 2.9
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-definition"
    source:
      version: 1.3.9
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-declarative-agent"
    source:
      version: 1.1.1
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-extensions"
    source:
      version: 1.3.9
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: 2.74
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-input-step"
    source:
      version: 2.11
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: 2.35
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-milestone-step"
    source:
      version: 1.3.1
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-api"
    source:
      version: 1.3.9
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-multibranch"
    source:
      version: 2.21
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      version: 2.34
  - groupId: "org.jenkins-ci.plugins.pipeline-stage-view"
    artifactId: "pipeline-rest-api"
    source:
      version: 2.12
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: 2.9
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps-global-lib"
    source:
      version: 2.15
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-stage-step"
    source:
      version: 2.3
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-stage-tags-metadata"
    source:
      version: 1.3.9
  - groupId: "org.jenkins-ci.plugins.pipeline-stage-view"
    artifactId: "pipeline-stage-view"
    source:
      version: 2.12
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: 2.20
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: 3.3
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "plain-credentials"
    source:
      version: 1.5
  - groupId: "com.sonyericsson.hudson.plugins.rebuild"
    artifactId: "rebuild"
    source:
      version: 1.31
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "run-condition"
    source:
      version: 1.2
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: 2.6.3
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: 1.66
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-agent"
    source:
      version: 1.17
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-credentials"
    source:
      version: 1.17.3
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-slaves"
    source:
      version: 1.30.2
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "stash-pullrequest-builder"
    source:
      version: 1.13
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: 1.20
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "support-core"
    source:
      version: 2.62
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "token-macro"
    source:
      version: 2.8
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "variant"
    source:
      version: 1.3
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "windows-slaves"
    source:
      version: 1.5
systemProperties: {
    jenkins.model.Jenkins.slaveAgentPort: "3737",
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true",
    hudson.model.DownloadService.never: "true",
    hudson.model.UpdateCenter.never: "true"}
